[package]
name = "operations-companion"
version = "0.1.0"
description = "运营工具快捷菜单"
authors = ["Leshuazf"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-global-shortcut = "2"
